#!/bin/bash
#
# I3WM
# autostart apps without desktop entry (started with dapper)
#   needs: [nitrogen]
#          [dunst]
#          [compton]
#
# file: ~/.config/i3/autostart
# v0.4 / 2015.09.19
#
# (c) 2015 Bernd Busse
#

# (re)set wallpaper with nitrogen
nitrogen --restore &

# start notification-daemon 'dunst'
if [[ -z $(pgrep dunst) ]]; then
    dunst &
fi

# start compositor 'compton'
if [[ -z $(pgrep compton) ]]; then
    compton &
fi

