#!/bin/bash
#
# I3WM
# autostart apps without desktop entry (started with dapper)
#   needs: [nitrogen]
#          [dunst]
#          [compton]
#          [pasystray]
#
# file: ~/.config/i3/autostart
# v0.3.1 / 2015.01.25
#
# (c) 2015 Bernd Busse
#

# (re)set wallpaper with nitrogen
nitrogen --restore &

# start notification-daemon 'dunst'
if [[ -z $(pgrep dunst) ]]; then
    dunst &
fi

# start compositor 'compton'
if [[ -z $(pgrep compton) ]]; then
    compton &
fi

# start audio 'jack-rack' and 'qjackctl' only on desktop computer
if [ ${HOSTNAME} == "sachnix" ]; then
    if [[ -z $(pgrep jack-rack) ]]; then
        sleep 5 && jack-rack -n -c 6 ${HOME}/.config/jack/equalizer &
    fi
    if [[ -z $(pgrep qjackctl) ]]; then
        qjackctl &
    fi
    sleep 5 && pactl -- set-sink-volume @DEFAULT_SINK@ 20% &
fi

