#!/bin/bash
#
# I3WM
# wrapper for j4status to display fancy JSON tags for i3bar
#   needs: [j4status]
#
# file: ~/.config/i3/i3bar-j4status
# v0.1 / 2014.12.24
#
# (c) 2014 Bernd Busse
#

# Set Colors for Conky
#export PANEL_BACKGROUND='#0C0C0C'
#export PANEL_FOREGROUND='#FFFFFF'
#export PANEL_HIGHLIGHT='#1793D1'
#export PANEL_INACTIVE='#3F3F3F'

# JSON header
#echo '{"version": 1, "click_events": false}'
# Begin endless array
#echo '['
# Send first empyt block
#echo '[],'

# find config file
_CONFIG="${I3_CONFIG}/i3bar-j4statusrc-${HOSTNAME}"
if [[ ! -e "${_CONFIG}" ]]; then
    _CONFIG="${I3_CONFIG}/i3bar-j4statusrc"
fi

# send endless updates
exec j4status -c "${_CONFIG}"

