#!/bin/sh
#
# I3WM
# wrapper for conky to send JSON tags to i3bar
#   needs: [conky]
#
# file: ~/.config/i3/i3bar-conky
# v0.1 / 2014.12.08
#
# (c) 2014 Bernd Busse
#

# Set Colors for Conky
export PANEL_BACKGROUND='#0C0C0C'
export PANEL_FORGEGROUND='#FFFFFF'
export PANEL_HIGHLIGHT='#1793D1'
export PANEL_INACTIVE='#3F3F3F'


# JSON header
echo '{"version": 1, "click_events": false}'
# Begin endless array
echo '['
# Send first empyt block
echo '[],'

# Send endlessly conky blocks
_CONFIG="${I3_CONFIG}/i3bar-conkyrc"
exec conky -c ${_CONFIG}

